baseURL       = 'https://jmooring.github.io/hosting-github-pages-git-lfs/'
languageCode  = 'en-US'
title         = 'Hosting Test - GitHub Pages with Git LFS'
enableGitInfo = true

# -----------------------------------------------------------------------------
# Caches
# -----------------------------------------------------------------------------

[caches.images]
  dir = ':cacheDir/images'

# -----------------------------------------------------------------------------
# Markup
# -----------------------------------------------------------------------------

[markup.goldmark.renderHooks.image]
  enableDefault = true

[markup.goldmark.renderHooks.link]
  enableDefault = true

# -----------------------------------------------------------------------------
# Menus
# -----------------------------------------------------------------------------

[[menus.main]]
  name    = 'Home'
  pageRef = '/'
  weight  = 10

[[menus.main]]
  name    = 'Articles'
  pageRef = '/articles'
  weight  = 20

[[menus.main]]
  name    = 'Books'
  pageRef = '/books'
  weight  = 30

[[menus.main]]
  name    = 'Tags'
  pageRef = '/tags'
  weight  = 40

[[menus.main]]
  name    = 'Tests'
  pageRef = '/tests'
  weight  = 50

# -----------------------------------------------------------------------------
# Module
# -----------------------------------------------------------------------------

[module.hugoVersion]
  extended = true
  min      = '0.147.1'

[[module.imports]]
  path = 'github.com/jmooring/hugo-module-content'
